@startuml
header "©2023 Chris Walsh <chris.is.rad@pm.me>"
title "PGPThing console app workflow"
start
repeat
:get keys;
if(key exists?) then (yes)
    :set key;
    note left: how do we store this?
    :encrypt;
    stop
else (no)
    :gen key;
endif
footer "page 1/1"
@enduml